name: Deploy to deploy-docs Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Build da documentação
      - name: Build documentation
        run: npm run build

      # Deploy para branch deploy-docs
      - name: Deploy to deploy-docs branch
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}