name: Deploy Docsify

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - uses: actions/checkout@v3

      # Configurar o Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Instalar dependências com npm
      - run: npm install

      # Validar se a documentação está gerada
      - run: npm run build

      # Deploy para o GitHub Pages na branch deploy-docs
      - run: |
          npm run deploy
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -b deploy-docs
          git add .
          git commit -m "Deploy docs to deploy-docs branch"
          git push --force origin deploy-docs
